### ISSUE TITLE
some bug when i build project 

### ISSUE THREAD

**Issue by phucpeta** [Appdynamics/redis-monitoring-extension#15]
there are some logs:
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  7.080 s
[INFO] Finished at: 2022-06-22T10:30:21+07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project redis-monitoring-extension: There are test failures.
[ERROR]
[ERROR] Please refer to C:\redis-monitoring-extension-master\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

i'm using C:\redis-monitoring-extension-master>mvn -v
Apache Maven 3.8.5 (3599d3414f046de2324203b78ddcf9b5e4388aa0)
Maven home: C:\apache-maven-3.8.5
Java version: 1.8.0_45, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk1.8.0_45\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows server 2012 r2", version: "6.3", arch: "amd64", family: "windows"

**Comment by yu3yu3m** [comment]
Can you please try building the artifact using following command and see if you are able to build it successfully?
mvn clean install -DskipTests

**Comment by phucpeta** [comment]
> Can you please try building the artifact using following command and see if you are able to build it successfully? mvn clean install -DskipTests

**yeah , it is builded successfully ...**
but i don't know why,,,
![image](https://user-images.githubusercontent.com/104067392/175894273-50851d3d-363e-4086-aba8-568bf027f0de.png)
normally i download zip file from github, in another extension i can use command " mvn clean install" can run smothly
....
today i try to clone repo by using githup desktop , it can build success without -DskipTests 
i dont know why LOL
