### ISSUE TITLE
Please add a licensing document

### ISSUE THREAD

**Issue by sushantappdynamics** [Appdynamics/redis-monitoring-extension#4]
Could you please add a licensing document so that customers who wish to use the extension understand licensing costs etc.

**Comment by ravigiroti** [comment]
All of our extensions are OSS and are provided free of charge. That makes your point about a licensing document moot.

**Comment by sushantappdynamics** [comment]
I understand. I was thinking along the lines of open-source licenses. As an example, the ``active-mq`` extension includes an Apache license. https://github.com/Appdynamics/activemq-monitoring-extension.
