### ISSUE TITLE
encryptionKey is missing on the config.yml

### ISSUE THREAD

**Issue by ymedlop** [Appdynamics/redis-monitoring-extension#8]
Hi,

Thanks for your work. I was following your instructions to run the agent with this extension but I have a error on this [ line 90](https://github.com/Appdynamics/redis-monitoring-extension/blob/master/src/main/java/com/appdynamics/extensions/redis/RedisMonitorTask.java#L90)

        String encryptionKey = configMap.get("encryptionKey").toString();

Solution: **encryptionKey** was missing on my config.yml.

I was using your [config.yml examples](https://github.com/Appdynamics/redis-monitoring-extension/tree/master/src/test/resources/conf). Could you fix it ?

Thanks

**Comment by satish-m** [comment]
Please use this [config.yml ](https://github.com/Appdynamics/redis-monitoring-extension/blob/master/src/main/resources/conf/config.yml)file

**Comment by ymedlop** [comment]
Thanks you!
